### ISSUE TITLE
Refactor to avoid code duplication

### ISSUE THREAD

**Issue by thalesfragoso** [thejpster/embedded-sdmmc-rs#10]
Right now there is a lot of code duplication between `Fat32Volume` and `Fat16Volume` types. Since the filesystem type is only known at runtime, everything gets compiled in. It might be better to refactor both into a single type and do the matching internally instead of outside, the downside is that not everything translates between the two, it would need more fields with `Option` in the struct and probably some more methods would have to be made failable.

**Comment by thejpster** [comment]
Good point, I agree.
